import React from 'react'

function About() {
  return (
    <div>About</div>
  )
}

export default About
export const metadata = {
    title: "Ecotrand - About",
    description: "Generated by create next app",
  };