import React from 'react'
import './about.scss'
import Link from 'next/link';
import Image from 'next/image';
import man1 from '../../img/quote-1.png'
import sign from '../../img/signature.png'

function About() {
  return (
    <>

      <section className="about-page ">
        <div className="bg-container py-48 flex flex-col justify-center items-center">
          <h2 className='text-white sm:text-7xl text-5xl font-bold  text-stroke'>About Us</h2>
          <p className='py-5 text-white'>
            <Link href="/" className='text-white hover:text-gray-800'>Home </Link>
            / Pages /
            <Link href="/about" className='text-gray-800'> About US</Link>
          </p>

        </div>

        <div className="about-main py-40">
          <div className="container mx-auto max-w-[1400px] px-10 md:flex">
            <div className='md:w-1/2 w-full'>
              <h2 className='relative'>
                <span className='text-black text-7xl sm:text-9xl font-bold text-stroke-black back-text'>Hey!</span>
                <span className='text-black text-4xl sm:text-7xl font-bold front-text'>We’re building a better future</span>
              </h2>
            </div>
            <div className='md:w-1/2 w-full mt-5 md:mt-0'>
              <p>
                <span className='text-black'>We’re among the world’s leading renewable energy solutions providers that is revolutionising and redefining the way sustainable energy sources are harnessed across the world.</span>
                <br /> <br />
                <span className="text-gray-500">Nulla quis lorem ut libero malesuada feugiat. Proin eget tortor risus. Curabitur non nulla sit amet nisl tempus convallis quis ac lectus. Cras ultricies ligula sed magna dictum porta. Donec sollicitudin molestie malesuada. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae.
                  <br /> <br />
                  Auctor sit amet aliquam vel, ullamcorper sit amet ligula. Donec rutrum congue leo eget malesuada. Curabitur aliquet quam id dui posuere blandit curabitur arcu erat.</span>
              </p>

              <div className='flex gap-10 mt-10 items-center flex-wrap sm:flex-nowrap'>

                <div>
                  <Image src={man1} width={0} height={0} alt='a man'></Image>
                </div>
                <div className='flex flex-col gap-3'>
                  <h5 className='text-black font-semibold'>John A Soul</h5>
                  <p className='text-gray-500 uppercase text-sm'>Founder</p>
                </div>

                <div>
                  <Image src={sign} width={0} height={0} alt='signature'></Image>
                </div>

              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  )
}

export default About
export const metadata = {
  title: "Ecotrand - About",
  description: "Generated by create next app",
};